language: node_js
node_js:
  - 0.8
services:
  - redis-server
before_script:
  - "export NODE_ENV=test"
  - "npm start&"
script:
  - "npm test"
  - "./node_modules/mocha/bin/mocha --ignore-leaks test/unit/*"